# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "virtio_pci" "virtio_scsi" "sr_mod" "virtio_blk" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-5321adc7-3fa0-440a-800c-5af65c7f5b43";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-5321adc7-3fa0-440a-800c-5af65c7f5b43".device = "/dev/disk/by-uuid/5321adc7-3fa0-440a-800c-5af65c7f5b43";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/1B37-E012";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
